-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS "BeClever"."Employees"
(
    "idEmployee" serial NOT NULL,
    first_name character varying(50) NOT NULL,
    last_name character varying(50) NOT NULL,
    gender character varying(1) NOT NULL,
    "idDepartments" integer NOT NULL,
    PRIMARY KEY ("idEmployee")
);

CREATE TABLE IF NOT EXISTS "BeClever"."Registers"
(
    "idRegister" serial NOT NULL,
    "idEmployee" integer NOT NULL,
    date_time timestamp without time zone NOT NULL,
    register_type character varying(20) NOT NULL,
    "idBusiness" integer NOT NULL,
    PRIMARY KEY ("idRegister")
);

CREATE TABLE IF NOT EXISTS "BeClever"."Business"
(
    "idBusiness" serial NOT NULL,
    location_name character varying(100) NOT NULL,
    PRIMARY KEY ("idBusiness")
);

CREATE TABLE IF NOT EXISTS "BeClever"."Departments"
(
    "idDepartment" serial NOT NULL,
    department_name character varying(100) NOT NULL,
    PRIMARY KEY ("idDepartment")
);

ALTER TABLE IF EXISTS "BeClever"."Employees"
    ADD CONSTRAINT "FK_DEPARTMENT" FOREIGN KEY ("idDepartments")
    REFERENCES "BeClever"."Departments" ("idDepartment") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS "BeClever"."Registers"
    ADD CONSTRAINT "FK_EMPLOYEE" FOREIGN KEY ("idEmployee")
    REFERENCES "BeClever"."Employees" ("idEmployee") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS "BeClever"."Registers"
    ADD CONSTRAINT "FK_BUSINESS" FOREIGN KEY ("idBusiness")
    REFERENCES "BeClever"."Business" ("idBusiness") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;